; Auto-generated. Do not edit!


(cl:in-package magic_object_finder-msg)


;//! \htmlinclude magicObjectFinderResult.msg.html

(cl:defclass <magicObjectFinderResult> (roslisp-msg-protocol:ros-message)
  ((found_object_code
    :reader found_object_code
    :initarg :found_object_code
    :type cl:integer
    :initform 0)
   (object_pose
    :reader object_pose
    :initarg :object_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass magicObjectFinderResult (<magicObjectFinderResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <magicObjectFinderResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'magicObjectFinderResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name magic_object_finder-msg:<magicObjectFinderResult> is deprecated: use magic_object_finder-msg:magicObjectFinderResult instead.")))

(cl:ensure-generic-function 'found_object_code-val :lambda-list '(m))
(cl:defmethod found_object_code-val ((m <magicObjectFinderResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader magic_object_finder-msg:found_object_code-val is deprecated.  Use magic_object_finder-msg:found_object_code instead.")
  (found_object_code m))

(cl:ensure-generic-function 'object_pose-val :lambda-list '(m))
(cl:defmethod object_pose-val ((m <magicObjectFinderResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader magic_object_finder-msg:object_pose-val is deprecated.  Use magic_object_finder-msg:object_pose instead.")
  (object_pose m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<magicObjectFinderResult>)))
    "Constants for message type '<magicObjectFinderResult>"
  '((:SUCCESS . 0)
    (:OBJECT_FOUND . 0)
    (:OBJECT_NOT_FOUND . 1)
    (:OBJECT_FINDER_CANCELLED . 4))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'magicObjectFinderResult)))
    "Constants for message type 'magicObjectFinderResult"
  '((:SUCCESS . 0)
    (:OBJECT_FOUND . 0)
    (:OBJECT_NOT_FOUND . 1)
    (:OBJECT_FINDER_CANCELLED . 4))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <magicObjectFinderResult>) ostream)
  "Serializes a message object of type '<magicObjectFinderResult>"
  (cl:let* ((signed (cl:slot-value msg 'found_object_code)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'object_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <magicObjectFinderResult>) istream)
  "Deserializes a message object of type '<magicObjectFinderResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'found_object_code) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'object_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<magicObjectFinderResult>)))
  "Returns string type for a message object of type '<magicObjectFinderResult>"
  "magic_object_finder/magicObjectFinderResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'magicObjectFinderResult)))
  "Returns string type for a message object of type 'magicObjectFinderResult"
  "magic_object_finder/magicObjectFinderResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<magicObjectFinderResult>)))
  "Returns md5sum for a message object of type '<magicObjectFinderResult>"
  "6b74d9ac7a843636175b07cfedbdce29")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'magicObjectFinderResult)))
  "Returns md5sum for a message object of type 'magicObjectFinderResult"
  "6b74d9ac7a843636175b07cfedbdce29")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<magicObjectFinderResult>)))
  "Returns full string definition for message of type '<magicObjectFinderResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%int32 SUCCESS =0 ~%int32 OBJECT_FOUND=0 #synonym for SUCCESS~%int32 OBJECT_NOT_FOUND=1~%int32 OBJECT_FINDER_CANCELLED=4~%#return the identified pose here:~%int32 found_object_code~%geometry_msgs/PoseStamped object_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'magicObjectFinderResult)))
  "Returns full string definition for message of type 'magicObjectFinderResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%int32 SUCCESS =0 ~%int32 OBJECT_FOUND=0 #synonym for SUCCESS~%int32 OBJECT_NOT_FOUND=1~%int32 OBJECT_FINDER_CANCELLED=4~%#return the identified pose here:~%int32 found_object_code~%geometry_msgs/PoseStamped object_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <magicObjectFinderResult>))
  (cl:+ 0
     4
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'object_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <magicObjectFinderResult>))
  "Converts a ROS message object to a list"
  (cl:list 'magicObjectFinderResult
    (cl:cons ':found_object_code (found_object_code msg))
    (cl:cons ':object_pose (object_pose msg))
))
