// Generated by gencpp from file coordinator/CoordinatorSrvResponse.msg
// DO NOT EDIT!


#ifndef COORDINATOR_MESSAGE_COORDINATORSRVRESPONSE_H
#define COORDINATOR_MESSAGE_COORDINATORSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coordinator
{
template <class ContainerAllocator>
struct CoordinatorSrvResponse_
{
  typedef CoordinatorSrvResponse_<ContainerAllocator> Type;

  CoordinatorSrvResponse_()
    : rtn_code(0)  {
    }
  CoordinatorSrvResponse_(const ContainerAllocator& _alloc)
    : rtn_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _rtn_code_type;
  _rtn_code_type rtn_code;





  typedef boost::shared_ptr< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CoordinatorSrvResponse_

typedef ::coordinator::CoordinatorSrvResponse_<std::allocator<void> > CoordinatorSrvResponse;

typedef boost::shared_ptr< ::coordinator::CoordinatorSrvResponse > CoordinatorSrvResponsePtr;
typedef boost::shared_ptr< ::coordinator::CoordinatorSrvResponse const> CoordinatorSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coordinator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'baxter_trajectory_streamer': ['/home/hanbin/ros_ws/devel/share/baxter_trajectory_streamer/msg'], 'roscpp': ['/opt/ros/kinetic/share/roscpp/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'arm7dof_traj_as': ['/home/hanbin/ros_ws/devel/share/arm7dof_traj_as/msg'], 'gazebo_msgs': ['/home/hanbin/ros_ws/src/learning_ros_external_pkgs_kinetic/gazebo_ros_pkgs/gazebo_msgs/msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'baxter_core_msgs': ['/home/hanbin/ros_ws/src/learning_ros_external_pkgs_kinetic/baxter_common/baxter_core_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'coordinator': ['/home/hanbin/ros_ws/devel/share/coordinator/msg'], 'object_grabber': ['/home/hanbin/ros_ws/devel/share/object_grabber/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tf': ['/opt/ros/kinetic/share/tf/cmake/../msg'], 'cartesian_planner': ['/home/hanbin/ros_ws/devel/share/cartesian_planner/msg'], 'pcl_msgs': ['/opt/ros/kinetic/share/pcl_msgs/cmake/../msg'], 'object_finder': ['/home/hanbin/ros_ws/devel/share/object_finder/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42f2b282ebf8297c4a5d72fb856688c7";
  }

  static const char* value(const ::coordinator::CoordinatorSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42f2b282ebf8297cULL;
  static const uint64_t static_value2 = 0x4a5d72fb856688c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coordinator/CoordinatorSrvResponse";
  }

  static const char* value(const ::coordinator::CoordinatorSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 rtn_code\n\
\n\
";
  }

  static const char* value(const ::coordinator::CoordinatorSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rtn_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CoordinatorSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coordinator::CoordinatorSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coordinator::CoordinatorSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "rtn_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rtn_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COORDINATOR_MESSAGE_COORDINATORSRVRESPONSE_H
