// Generated by gencpp from file sin_commander_service/SinCommanderMsg.msg
// DO NOT EDIT!


#ifndef SIN_COMMANDER_SERVICE_MESSAGE_SINCOMMANDERMSG_H
#define SIN_COMMANDER_SERVICE_MESSAGE_SINCOMMANDERMSG_H

#include <ros/service_traits.h>


#include <sin_commander_service/SinCommanderMsgRequest.h>
#include <sin_commander_service/SinCommanderMsgResponse.h>


namespace sin_commander_service
{

struct SinCommanderMsg
{

typedef SinCommanderMsgRequest Request;
typedef SinCommanderMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SinCommanderMsg
} // namespace sin_commander_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sin_commander_service::SinCommanderMsg > {
  static const char* value()
  {
    return "1934939e811673ac6de96fd9859814cf";
  }

  static const char* value(const ::sin_commander_service::SinCommanderMsg&) { return value(); }
};

template<>
struct DataType< ::sin_commander_service::SinCommanderMsg > {
  static const char* value()
  {
    return "sin_commander_service/SinCommanderMsg";
  }

  static const char* value(const ::sin_commander_service::SinCommanderMsg&) { return value(); }
};


// service_traits::MD5Sum< ::sin_commander_service::SinCommanderMsgRequest> should match 
// service_traits::MD5Sum< ::sin_commander_service::SinCommanderMsg > 
template<>
struct MD5Sum< ::sin_commander_service::SinCommanderMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sin_commander_service::SinCommanderMsg >::value();
  }
  static const char* value(const ::sin_commander_service::SinCommanderMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sin_commander_service::SinCommanderMsgRequest> should match 
// service_traits::DataType< ::sin_commander_service::SinCommanderMsg > 
template<>
struct DataType< ::sin_commander_service::SinCommanderMsgRequest>
{
  static const char* value()
  {
    return DataType< ::sin_commander_service::SinCommanderMsg >::value();
  }
  static const char* value(const ::sin_commander_service::SinCommanderMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sin_commander_service::SinCommanderMsgResponse> should match 
// service_traits::MD5Sum< ::sin_commander_service::SinCommanderMsg > 
template<>
struct MD5Sum< ::sin_commander_service::SinCommanderMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sin_commander_service::SinCommanderMsg >::value();
  }
  static const char* value(const ::sin_commander_service::SinCommanderMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sin_commander_service::SinCommanderMsgResponse> should match 
// service_traits::DataType< ::sin_commander_service::SinCommanderMsg > 
template<>
struct DataType< ::sin_commander_service::SinCommanderMsgResponse>
{
  static const char* value()
  {
    return DataType< ::sin_commander_service::SinCommanderMsg >::value();
  }
  static const char* value(const ::sin_commander_service::SinCommanderMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIN_COMMANDER_SERVICE_MESSAGE_SINCOMMANDERMSG_H
