// Generated by gencpp from file sin_commander_service/SinCommanderMsgResponse.msg
// DO NOT EDIT!


#ifndef SIN_COMMANDER_SERVICE_MESSAGE_SINCOMMANDERMSGRESPONSE_H
#define SIN_COMMANDER_SERVICE_MESSAGE_SINCOMMANDERMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sin_commander_service
{
template <class ContainerAllocator>
struct SinCommanderMsgResponse_
{
  typedef SinCommanderMsgResponse_<ContainerAllocator> Type;

  SinCommanderMsgResponse_()
    : sin_velocity(0.0)  {
    }
  SinCommanderMsgResponse_(const ContainerAllocator& _alloc)
    : sin_velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _sin_velocity_type;
  _sin_velocity_type sin_velocity;





  typedef boost::shared_ptr< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SinCommanderMsgResponse_

typedef ::sin_commander_service::SinCommanderMsgResponse_<std::allocator<void> > SinCommanderMsgResponse;

typedef boost::shared_ptr< ::sin_commander_service::SinCommanderMsgResponse > SinCommanderMsgResponsePtr;
typedef boost::shared_ptr< ::sin_commander_service::SinCommanderMsgResponse const> SinCommanderMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sin_commander_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/kinetic/share/roscpp/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b20870355cb705aa117d3b478d7a30d";
  }

  static const char* value(const ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b20870355cb705aULL;
  static const uint64_t static_value2 = 0xa117d3b478d7a30dULL;
};

template<class ContainerAllocator>
struct DataType< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sin_commander_service/SinCommanderMsgResponse";
  }

  static const char* value(const ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 sin_velocity\n\
\n\
";
  }

  static const char* value(const ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sin_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SinCommanderMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sin_commander_service::SinCommanderMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "sin_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.sin_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIN_COMMANDER_SERVICE_MESSAGE_SINCOMMANDERMSGRESPONSE_H
