// Generated by gencpp from file object_grabber/object_grabberResult.msg
// DO NOT EDIT!


#ifndef OBJECT_GRABBER_MESSAGE_OBJECT_GRABBERRESULT_H
#define OBJECT_GRABBER_MESSAGE_OBJECT_GRABBERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_grabber
{
template <class ContainerAllocator>
struct object_grabberResult_
{
  typedef object_grabberResult_<ContainerAllocator> Type;

  object_grabberResult_()
    : return_code(0)
    , computed_move_time(0.0)  {
    }
  object_grabberResult_(const ContainerAllocator& _alloc)
    : return_code(0)
    , computed_move_time(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _return_code_type;
  _return_code_type return_code;

   typedef double _computed_move_time_type;
  _computed_move_time_type computed_move_time;



  enum {
    SUCCESS = 0,
    OBJECT_ACQUIRED = 0,
    FAILED_CANNOT_REACH = 1,
    FAILED_CANNOT_APPROACH = 2,
    FAILED_CANNOT_REACH_GRASP_POSE = 3,
    FAILED_CANNOT_REACH_DEPART_POSE = 4,
    FAILED_OBJECT_NOT_IN_GRIPPER = 5,
    FAILED_OBJECT_UNKNOWN = 6,
    OBJECT_GRABBER_BUSY = 7,
    OBJECT_GRABBER_CANCELLED = 8,
    FAILED_CANNOT_REACH_DESIRED_POSE = 9,
    FAILED_CANNOT_MOVE_CARTESIAN_FINE = 13,
    FAILED_CANNOT_MOVE_TO_PRE_POSE = 14,
    ACTION_CODE_UNKNOWN = 15,
    GRIPPER_IS_OPEN = 16,
    GRIPPER_IS_CLOSED = 17,
    GRIPPER_FAILURE = 18,
    PENDING = 19,
    OBJECT_DROPPED_OFF = 20,
    NO_KNOWN_GRASP_OPTIONS_THIS_GRIPPER_AND_OBJECT = 21,
  };


  typedef boost::shared_ptr< ::object_grabber::object_grabberResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_grabber::object_grabberResult_<ContainerAllocator> const> ConstPtr;

}; // struct object_grabberResult_

typedef ::object_grabber::object_grabberResult_<std::allocator<void> > object_grabberResult;

typedef boost::shared_ptr< ::object_grabber::object_grabberResult > object_grabberResultPtr;
typedef boost::shared_ptr< ::object_grabber::object_grabberResult const> object_grabberResultConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_grabber::object_grabberResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_grabber::object_grabberResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_grabber

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roscpp': ['/opt/ros/kinetic/share/roscpp/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'arm7dof_traj_as': ['/home/hanbin/ros_ws/devel/share/arm7dof_traj_as/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'baxter_core_msgs': ['/home/hanbin/ros_ws/src/learning_ros_external_pkgs_kinetic/baxter_common/baxter_core_msgs/msg'], 'object_grabber': ['/home/hanbin/ros_ws/devel/share/object_grabber/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg', '/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tf': ['/opt/ros/kinetic/share/tf/cmake/../msg'], 'cartesian_planner': ['/home/hanbin/ros_ws/devel/share/cartesian_planner/msg'], 'baxter_trajectory_streamer': ['/home/hanbin/ros_ws/devel/share/baxter_trajectory_streamer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_grabber::object_grabberResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_grabber::object_grabberResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_grabber::object_grabberResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_grabber::object_grabberResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_grabber::object_grabberResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_grabber::object_grabberResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_grabber::object_grabberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcf73739df5325dcb290850c3f1c9d26";
  }

  static const char* value(const ::object_grabber::object_grabberResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcf73739df5325dcULL;
  static const uint64_t static_value2 = 0xb290850c3f1c9d26ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_grabber::object_grabberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_grabber/object_grabberResult";
  }

  static const char* value(const ::object_grabber::object_grabberResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_grabber::object_grabberResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
#  response codes...\n\
int32 SUCCESS=0\n\
int32 OBJECT_ACQUIRED=0\n\
int32 FAILED_CANNOT_REACH=1\n\
int32 FAILED_CANNOT_APPROACH=2\n\
int32 FAILED_CANNOT_REACH_GRASP_POSE=3\n\
int32 FAILED_CANNOT_REACH_DEPART_POSE=4\n\
int32 FAILED_OBJECT_NOT_IN_GRIPPER=5\n\
int32 FAILED_OBJECT_UNKNOWN=6\n\
int32 OBJECT_GRABBER_BUSY=7\n\
int32 OBJECT_GRABBER_CANCELLED=8\n\
int32 FAILED_CANNOT_REACH_DESIRED_POSE=9\n\
int32 FAILED_CANNOT_MOVE_CARTESIAN_FINE=13\n\
int32 FAILED_CANNOT_MOVE_TO_PRE_POSE=14\n\
int32 ACTION_CODE_UNKNOWN=15\n\
int32 GRIPPER_IS_OPEN=16\n\
int32 GRIPPER_IS_CLOSED=17\n\
int32 GRIPPER_FAILURE=18\n\
int32 PENDING=19\n\
int32 OBJECT_DROPPED_OFF = 20\n\
int32 NO_KNOWN_GRASP_OPTIONS_THIS_GRIPPER_AND_OBJECT = 21\n\
\n\
int32 return_code\n\
#geometry_msgs/PoseStamped des_flange_pose_stamped_wrt_torso\n\
float64 computed_move_time\n\
";
  }

  static const char* value(const ::object_grabber::object_grabberResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_grabber::object_grabberResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_code);
      stream.next(m.computed_move_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct object_grabberResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_grabber::object_grabberResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_grabber::object_grabberResult_<ContainerAllocator>& v)
  {
    s << indent << "return_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.return_code);
    s << indent << "computed_move_time: ";
    Printer<double>::stream(s, indent + "  ", v.computed_move_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_GRABBER_MESSAGE_OBJECT_GRABBERRESULT_H
