(cl:defpackage magic_object_finder-msg
  (:use )
  (:export
   "<MAGICOBJECTFINDERACTION>"
   "MAGICOBJECTFINDERACTION"
   "<MAGICOBJECTFINDERACTIONFEEDBACK>"
   "MAGICOBJECTFINDERACTIONFEEDBACK"
   "<MAGICOBJECTFINDERACTIONGOAL>"
   "MAGICOBJECTFINDERACTIONGOAL"
   "<MAGICOBJECTFINDERACTIONRESULT>"
   "MAGICOBJECTFINDERACTIONRESULT"
   "<MAGICOBJECTFINDERFEEDBACK>"
   "MAGICOBJECTFINDERFEEDBACK"
   "<MAGICOBJECTFINDERGOAL>"
   "MAGICOBJECTFINDERGOAL"
   "<MAGICOBJECTFINDERRESULT>"
   "MAGICOBJECTFINDERRESULT"
  ))

