; Auto-generated. Do not edit!


(cl:in-package magic_object_finder-msg)


;//! \htmlinclude magicObjectFinderFeedback.msg.html

(cl:defclass <magicObjectFinderFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass magicObjectFinderFeedback (<magicObjectFinderFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <magicObjectFinderFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'magicObjectFinderFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name magic_object_finder-msg:<magicObjectFinderFeedback> is deprecated: use magic_object_finder-msg:magicObjectFinderFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <magicObjectFinderFeedback>) ostream)
  "Serializes a message object of type '<magicObjectFinderFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <magicObjectFinderFeedback>) istream)
  "Deserializes a message object of type '<magicObjectFinderFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<magicObjectFinderFeedback>)))
  "Returns string type for a message object of type '<magicObjectFinderFeedback>"
  "magic_object_finder/magicObjectFinderFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'magicObjectFinderFeedback)))
  "Returns string type for a message object of type 'magicObjectFinderFeedback"
  "magic_object_finder/magicObjectFinderFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<magicObjectFinderFeedback>)))
  "Returns md5sum for a message object of type '<magicObjectFinderFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'magicObjectFinderFeedback)))
  "Returns md5sum for a message object of type 'magicObjectFinderFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<magicObjectFinderFeedback>)))
  "Returns full string definition for message of type '<magicObjectFinderFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback: optional; ~%#int32 OBJECT_FINDER_BUSY=3 ~%#int32 fdbk~%~%~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'magicObjectFinderFeedback)))
  "Returns full string definition for message of type 'magicObjectFinderFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback: optional; ~%#int32 OBJECT_FINDER_BUSY=3 ~%#int32 fdbk~%~%~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <magicObjectFinderFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <magicObjectFinderFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'magicObjectFinderFeedback
))
