// Auto-generated. Do not edit!

// (in-package sin_commander_action_server.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class sinGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.amp = null;
      this.freq = null;
      this.cycles = null;
    }
    else {
      if (initObj.hasOwnProperty('amp')) {
        this.amp = initObj.amp
      }
      else {
        this.amp = 0.0;
      }
      if (initObj.hasOwnProperty('freq')) {
        this.freq = initObj.freq
      }
      else {
        this.freq = 0.0;
      }
      if (initObj.hasOwnProperty('cycles')) {
        this.cycles = initObj.cycles
      }
      else {
        this.cycles = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type sinGoal
    // Serialize message field [amp]
    bufferOffset = _serializer.float32(obj.amp, buffer, bufferOffset);
    // Serialize message field [freq]
    bufferOffset = _serializer.float32(obj.freq, buffer, bufferOffset);
    // Serialize message field [cycles]
    bufferOffset = _serializer.float32(obj.cycles, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type sinGoal
    let len;
    let data = new sinGoal(null);
    // Deserialize message field [amp]
    data.amp = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [freq]
    data.freq = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [cycles]
    data.cycles = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'sin_commander_action_server/sinGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ffeb59ebfe8b276c08f84c2c146723ca';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float32 amp
    float32 freq
    float32 cycles
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new sinGoal(null);
    if (msg.amp !== undefined) {
      resolved.amp = msg.amp;
    }
    else {
      resolved.amp = 0.0
    }

    if (msg.freq !== undefined) {
      resolved.freq = msg.freq;
    }
    else {
      resolved.freq = 0.0
    }

    if (msg.cycles !== undefined) {
      resolved.cycles = msg.cycles;
    }
    else {
      resolved.cycles = 0.0
    }

    return resolved;
    }
};

module.exports = sinGoal;
