// Generated by gencpp from file part_fetcher/PartFetcherResult.msg
// DO NOT EDIT!


#ifndef PART_FETCHER_MESSAGE_PARTFETCHERRESULT_H
#define PART_FETCHER_MESSAGE_PARTFETCHERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace part_fetcher
{
template <class ContainerAllocator>
struct PartFetcherResult_
{
  typedef PartFetcherResult_<ContainerAllocator> Type;

  PartFetcherResult_()
    : rtn_code(0)  {
    }
  PartFetcherResult_(const ContainerAllocator& _alloc)
    : rtn_code(0)  {
  (void)_alloc;
    }



   typedef int32_t _rtn_code_type;
  _rtn_code_type rtn_code;





  typedef boost::shared_ptr< ::part_fetcher::PartFetcherResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::part_fetcher::PartFetcherResult_<ContainerAllocator> const> ConstPtr;

}; // struct PartFetcherResult_

typedef ::part_fetcher::PartFetcherResult_<std::allocator<void> > PartFetcherResult;

typedef boost::shared_ptr< ::part_fetcher::PartFetcherResult > PartFetcherResultPtr;
typedef boost::shared_ptr< ::part_fetcher::PartFetcherResult const> PartFetcherResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::part_fetcher::PartFetcherResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace part_fetcher

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'roscpp': ['/opt/ros/kinetic/share/roscpp/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'arm7dof_traj_as': ['/home/hanbin/ros_ws/devel/share/arm7dof_traj_as/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'part_fetcher': ['/home/hanbin/ros_ws/devel/share/part_fetcher/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'baxter_core_msgs': ['/home/hanbin/ros_ws/src/learning_ros_external_pkgs_kinetic/baxter_common/baxter_core_msgs/msg'], 'object_grabber': ['/home/hanbin/ros_ws/devel/share/object_grabber/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tf': ['/opt/ros/kinetic/share/tf/cmake/../msg'], 'cartesian_planner': ['/home/hanbin/ros_ws/devel/share/cartesian_planner/msg'], 'baxter_trajectory_streamer': ['/home/hanbin/ros_ws/devel/share/baxter_trajectory_streamer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::part_fetcher::PartFetcherResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::part_fetcher::PartFetcherResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::part_fetcher::PartFetcherResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42f2b282ebf8297c4a5d72fb856688c7";
  }

  static const char* value(const ::part_fetcher::PartFetcherResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42f2b282ebf8297cULL;
  static const uint64_t static_value2 = 0x4a5d72fb856688c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "part_fetcher/PartFetcherResult";
  }

  static const char* value(const ::part_fetcher::PartFetcherResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
int32 rtn_code\n\
";
  }

  static const char* value(const ::part_fetcher::PartFetcherResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rtn_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PartFetcherResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::part_fetcher::PartFetcherResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::part_fetcher::PartFetcherResult_<ContainerAllocator>& v)
  {
    s << indent << "rtn_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rtn_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PART_FETCHER_MESSAGE_PARTFETCHERRESULT_H
